출처 : pytorch 튜트리얼

In [1]:
import torch
x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad = True)
b = torch.randn(3, requires_grad = True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [2]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x7fce2476f4d0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x7fce24791410>


In [3]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0103, 0.3066, 0.1138],
        [0.0103, 0.3066, 0.1138],
        [0.0103, 0.3066, 0.1138],
        [0.0103, 0.3066, 0.1138],
        [0.0103, 0.3066, 0.1138]])
tensor([0.0103, 0.3066, 0.1138])


In [4]:
z = torch.matmul(x, w) + b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w) + b

print(z.requires_grad)

True
False


In [5]:
z = torch.matmul(x, w) + b
z_det = z.detach()
print(z_det.requires_grad)

False


In [6]:
inp = torch.eye(5, requires_grad = True)
out = (inp + 1).pow(2)
out.backward(torch.ones_like(inp), retain_graph = True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(inp), retain_graph = True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(inp), retain_graph = True)
print(f"\ncall after zeroing gradients \n{inp.grad}")

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.]])

call after zeroing gradients 
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
