출처 : pytorch 튜트리얼

In [1]:
import torch
import math

In [2]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[1.0637e-34, 0.0000e+00, 3.3631e-44, 0.0000e+00],
        [       nan, 6.4460e-44, 1.1578e+27, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 1.2121e+04, 7.1846e+22]])


In [4]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [5]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [6]:
x = torch.empty(2, 2, 3)
print(x.shape)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
tensor([[[1.0637e-34, 0.0000e+00, 3.3631e-44],
         [0.0000e+00,        nan, 0.0000e+00]],

        [[1.1578e+27, 1.1362e+30, 7.1547e+22],
         [4.5828e+30, 1.2121e+04, 7.1846e+22]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [9]:
a = torch.ones((2, 3), dtype = torch.int16)
print(a)

b = torch.rand((2, 3), dtype = torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[12.3902, 15.0541, 16.8179],
        [17.7174, 14.2091, 18.9694]], dtype=torch.float64)
tensor([[12, 15, 16],
        [17, 14, 18]], dtype=torch.int32)


Math & Logic with Pytorch Tensors

In [10]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours =twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [11]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

print(a * b)
# 다른것은 못 한다. 

RuntimeError: ignored

In [12]:
rand = torch.rand(2, 4)
doubled = rand * ( torch.ones(1, 4) * 2)
print(rand)
print(doubled)

tensor([[0.1332, 0.0023, 0.4945, 0.3857],
        [0.9883, 0.4762, 0.7242, 0.0776]])
tensor([[0.2663, 0.0045, 0.9890, 0.7715],
        [1.9767, 0.9524, 1.4484, 0.1553]])


In [17]:
# broadcast
a = torch.ones(4, 3, 2)
b = a * torch.rand( 3, 2)
print(b)
print(b.shape)

c = a * torch.rand( 3, 1)
print(c)
print(c.shape)

d = a * torch.rand( 1, 2)
print(d)
print(d.shape)

tensor([[[0.4460, 0.9289],
         [0.6293, 0.6264],
         [0.4704, 0.6077]],

        [[0.4460, 0.9289],
         [0.6293, 0.6264],
         [0.4704, 0.6077]],

        [[0.4460, 0.9289],
         [0.6293, 0.6264],
         [0.4704, 0.6077]],

        [[0.4460, 0.9289],
         [0.6293, 0.6264],
         [0.4704, 0.6077]]])
torch.Size([4, 3, 2])
tensor([[[0.4757, 0.4757],
         [0.5874, 0.5874],
         [0.4363, 0.4363]],

        [[0.4757, 0.4757],
         [0.5874, 0.5874],
         [0.4363, 0.4363]],

        [[0.4757, 0.4757],
         [0.5874, 0.5874],
         [0.4363, 0.4363]],

        [[0.4757, 0.4757],
         [0.5874, 0.5874],
         [0.4363, 0.4363]]])
torch.Size([4, 3, 2])
tensor([[[0.6339, 0.3208],
         [0.6339, 0.3208],
         [0.6339, 0.3208]],

        [[0.6339, 0.3208],
         [0.6339, 0.3208],
         [0.6339, 0.3208]],

        [[0.6339, 0.3208],
         [0.6339, 0.3208],
         [0.6339, 0.3208]],

        [[0.6339, 0.3208],
         [0.6339

In [19]:
a = torch.ones(4, 3, 2)
b = a * torch.rand(4, 3)  # dimensions must match last-to-first
c = a * torch.rand(   2, 3)
d = a * torch.rand((0,))

RuntimeError: ignored

more math

In [20]:
a = torch.rand(2, 4) * 2 - 1
print("common fuctions:")
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

common fuctions:
tensor([[0.2733, 0.5398, 0.8303, 0.0112],
        [0.4681, 0.0503, 0.6737, 0.4782]])
tensor([[1., -0., 1., 1.],
        [-0., 1., -0., 1.]])
tensor([[ 0., -1.,  0.,  0.],
        [-1.,  0., -1.,  0.]])
tensor([[ 0.2733, -0.5000,  0.5000,  0.0112],
        [-0.4681,  0.0503, -0.5000,  0.4782]])


In [23]:
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4  ])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)


Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


In [24]:
# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))


Bitwise XOR:
tensor([3, 2, 1])


In [25]:
# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  
print(torch.eq(d, e))


Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])


In [26]:
# reductions:
print('\nReduction ops:')
print(torch.max(d))        
print(torch.max(d).item()) 
print(torch.mean(d))       
print(torch.std(d))        
print(torch.prod(d))       
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2])))


Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [29]:
# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         
v2 = torch.tensor([0., 1., 0.])         
m1 = torch.rand(2, 2)                   
m2 = torch.tensor([[3., 0.], [0., 3.]]) 

print('\nVectors & Matrices:')
print(torch.cross(v2, v1))
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                 
print(torch.svd(m3))      


Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.9106, 0.8941],
        [0.7992, 0.0554]])
tensor([[2.7317, 2.6824],
        [2.3977, 0.1662]])
torch.return_types.svd(
U=tensor([[-0.8763, -0.4817],
        [-0.4817,  0.8763]]),
S=tensor([4.3015, 1.3897]),
V=tensor([[-0.8250,  0.5651],
        [-0.5651, -0.8250]]))


In [31]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4  ])
print('a: ')
print(a)
print(torch.sin(a))
print(a)

a: 
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])


In [32]:
b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4  ])
print('\nb: ')
print(b)
print(torch.sin_(b))
print(b)


b: 
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [34]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before: ')
print(a)
print(b)
print('\nAfter_adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter_multiplying:')
print(b.mul_(b))
print(b)

Before: 
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.2174, 0.2038],
        [0.2881, 0.2677]])

After_adding:
tensor([[1.2174, 1.2038],
        [1.2881, 1.2677]])
tensor([[1.2174, 1.2038],
        [1.2881, 1.2677]])
tensor([[0.2174, 0.2038],
        [0.2881, 0.2677]])

After_multiplying:
tensor([[0.0473, 0.0415],
        [0.0830, 0.0717]])
tensor([[0.0473, 0.0415],
        [0.0830, 0.0717]])


In [36]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out = c)
print(c)

assert c is d
assert id(c), old_id


tensor([[0., 0.],
        [0., 0.]])
tensor([[0.3925, 0.4236],
        [0.8706, 1.0576]])


In [37]:
torch.rand(2, 2, out = c)
print(c)
assert id(c), old_id

tensor([[0.1619, 0.0425],
        [0.0313, 0.5074]])


In [39]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561
print(b)

tensor([[  1., 561.],
        [  1.,   1.]])


In [41]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a
print(torch.eq(a, b))

a[0][1] = 561
print(b)

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [43]:
a = torch.rand(2, 2, requires_grad = True)
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.8454, 0.1194],
        [0.7245, 0.6522]], requires_grad=True)
tensor([[0.8454, 0.1194],
        [0.7245, 0.6522]], grad_fn=<CloneBackward0>)
tensor([[0.8454, 0.1194],
        [0.7245, 0.6522]])
tensor([[0.8454, 0.1194],
        [0.7245, 0.6522]], requires_grad=True)


Moving to GPU

In [45]:
if torch.cuda.is_available():
    print("we have a GPU")
else:
    print('Sorry, CPU only')

we have a GPU


In [46]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device = 'cuda')
    print(gpu_rand)
else:
    print('Sorry, CPU only')

tensor([[0.3344, 0.2640],
        [0.2119, 0.0582]], device='cuda:0')


In [48]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
    print(my_device)
else:
    my_device = torch.device('cpu') 
print('Device : {}'.format(my_device))

x = torch.rand(2, 2, device = my_device)
print(x)

cuda
Device : cuda
tensor([[0.0024, 0.6778],
        [0.2441, 0.6812]], device='cuda:0')


In [50]:
y = torch.rand(2, 2)
y = y.to(my_device)

Manipulating Tensor shapes

In [51]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [52]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)

tensor([[[[[0.7705]]]]])


In [53]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.0227, 0.2371, 0.5902, 0.5563, 0.1966, 0.2077, 0.8869, 0.7977, 0.4532,
         0.1746, 0.2414, 0.2355, 0.9062, 0.2904, 0.2634, 0.6897, 0.3774, 0.0906,
         0.3839, 0.4696]])
torch.Size([20])
tensor([0.0227, 0.2371, 0.5902, 0.5563, 0.1966, 0.2077, 0.8869, 0.7977, 0.4532,
        0.1746, 0.2414, 0.2355, 0.9062, 0.2904, 0.2634, 0.6897, 0.3774, 0.0906,
        0.3839, 0.4696])
tensor([0.0227, 0.2371, 0.5902, 0.5563, 0.1966, 0.2077, 0.8869, 0.7977, 0.4532,
        0.1746, 0.2414, 0.2355, 0.9062, 0.2904, 0.2634, 0.6897, 0.3774, 0.0906,
        0.3839, 0.4696])
torch.Size([2, 2])
torch.Size([2, 2])


In [54]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)
c = b.unsqueeze(1)
print(c.shape)
print(a * c)

torch.Size([3, 1])
tensor([[[0.3702, 0.3702],
         [0.2488, 0.2488],
         [0.9021, 0.9021]],

        [[0.3702, 0.3702],
         [0.2488, 0.2488],
         [0.9021, 0.9021]],

        [[0.3702, 0.3702],
         [0.2488, 0.2488],
         [0.9021, 0.9021]],

        [[0.3702, 0.3702],
         [0.2488, 0.2488],
         [0.9021, 0.9021]]])


In [55]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [58]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape( 6 * 20 * 20)
print(input1d.shape)

print(torch.reshape(output3d, (6 * 20 * 20, )).shape)

torch.Size([2400])


In [59]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [60]:
pytorch_rand = torch.rand([2, 3])
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.7201, 0.0231, 0.4332],
        [0.5725, 0.1018, 0.1840]])
[[0.7201188  0.02313733 0.43317455]
 [0.5724983  0.10176712 0.18398839]]


In [62]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1][1] = 17
print(numpy_array)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 1.  1.  1.]
 [ 1. 23.  1.]]
