출처 : pytorch 튜트리얼

In [1]:
import torch

class TinyModel(torch.nn.Module):
    def __init__(self):
        super(TinyModel, self).__init__()

        self.linear1 = torch.nn.Linear(100, 200)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(200, 10)
        self.softmax = torch.nn.Softmax()

    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.linear2(x)
        x = self.softmax(x)
        return x

tinymodel = TinyModel()

print("The model:")
print(tinymodel)

print('\n\nJust one layer:')
print(tinymodel.linear2)

print('\n\nModel params:')
for param in tinymodel.parameters():
    print(param)

print('\n\nLayer params:')
for param in tinymodel.linear2.parameters():
    print(param)

The model:
TinyModel(
  (linear1): Linear(in_features=100, out_features=200, bias=True)
  (activation): ReLU()
  (linear2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)


Just one layer:
Linear(in_features=200, out_features=10, bias=True)


Model params:
Parameter containing:
tensor([[ 0.0830, -0.0728, -0.0939,  ..., -0.0076,  0.0230,  0.0279],
        [-0.0705, -0.0125,  0.0991,  ...,  0.0567, -0.0064, -0.0055],
        [-0.0758, -0.0297,  0.0660,  ...,  0.0447, -0.0456,  0.0831],
        ...,
        [ 0.0452, -0.0111,  0.0073,  ...,  0.0098,  0.0136, -0.0449],
        [ 0.0911, -0.0985,  0.0270,  ..., -0.0502,  0.0631, -0.0836],
        [-0.0698, -0.0385, -0.0911,  ..., -0.0180,  0.0158,  0.0663]],
       requires_grad=True)
Parameter containing:
tensor([-0.0140, -0.0428, -0.0100,  0.0430, -0.0629,  0.0035, -0.0201, -0.0278,
        -0.0119,  0.0933, -0.0860,  0.0240,  0.0504,  0.0514,  0.0163, -0.0086,
         0.0207, -0.0839,  0.0399,  0.02

In [2]:
lin = torch.nn.Linear(3, 2)
x = torch.rand(1, 3)
print('Input:')
print(x)

print('\n\nWeight and Bias parameters:')
for param in lin.parameters():
    print(param)

y = lin(x)
print('\n\n Output:')
print(y)

Input:
tensor([[0.1684, 0.5848, 0.4501]])


Weight and Bias parameters:
Parameter containing:
tensor([[ 0.0320, -0.2892, -0.1916],
        [-0.1605, -0.5610,  0.1956]], requires_grad=True)
Parameter containing:
tensor([-0.2484, -0.1781], requires_grad=True)


 Output:
tensor([[-0.4983, -0.4451]], grad_fn=<AddmmBackward0>)


In [3]:
import torch.functional as F

class LeNet(torch.nn.Module):
    def __init__(self):
        super(LeNet, self).__init__()

        self.conv1 = torch.nn.Conv2d(1, 6, 5)
        self.conv2 = torch.nn.Conv2d(6, 16, 3)

        self.fc1 = torch.nn.Linear(16* 6* 6 , 120)
        self.fc2 = torch.nn.Linear(120, 84)
        self.fc3 = torch.nn.Linear(84, 10)
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

In [4]:
class LSTMTagger(torch.nn.Module):
    def __init__(self, embedding_dim, hidden_dim, vocab_size, tagset_size):
        super(LSTMTagger, self).__init__()
        self.hidden_dim = hidden_dim
        self.word_embeddings = torch.nn.Embedding(vocab_size, embedding_dim)
        self.lstm = torch.nn.LSTM(embedding_dim, hidden_dim)
        self.hidden2tag = torch.nn.Linear(hidden_dim, tagset_size)
    def forward(self, sentence):
        embeds = self.word_embeddings(sentence)
        lstm_out, _ = self.lstm(embeds.view(len(sentence), 1, -1))
        tag_space = self.hidden2tag(lstm_out.view(len(sentence), -1))
        tag_scores = F.log_softmax(tag_space, dim=1)
        return tag_scores

In [6]:
my_tensor = torch.rand(1, 6, 6)
print(my_tensor)

maxpool_layer = torch.nn.MaxPool2d(3)
print(maxpool_layer(my_tensor))

tensor([[[0.6414, 0.3338, 0.4516, 0.2821, 0.0566, 0.2937],
         [0.3063, 0.1187, 0.3687, 0.9547, 0.5831, 0.4924],
         [0.1094, 0.6331, 0.2956, 0.0129, 0.9637, 0.3472],
         [0.1065, 0.0875, 0.3278, 0.7253, 0.6574, 0.1303],
         [0.5328, 0.8269, 0.0289, 0.5605, 0.8296, 0.0252],
         [0.4445, 0.8777, 0.4970, 0.1080, 0.6325, 0.7004]]])
tensor([[[0.6414, 0.9637],
         [0.8777, 0.8296]]])


In [7]:
my_tensor = torch.rand(1, 4, 4) * 20 + 5
print(my_tensor)

print(my_tensor.mean())

norm_layer = torch.nn.BatchNorm1d(4)
normed_tensor = norm_layer(my_tensor)
print(normed_tensor)

print(normed_tensor.mean())

tensor([[[10.0346,  9.5914, 12.0334, 10.8625],
         [18.3711, 23.7965, 10.2899,  8.5109],
         [15.2025, 23.9936,  9.6637, 18.3529],
         [23.6622, 17.1001, 19.1651, 14.5885]]])
tensor(15.3262)
tensor([[[-0.6410, -1.1177,  1.5091,  0.2496],
         [ 0.5063,  1.3841, -0.8012, -1.0891],
         [-0.3086,  1.3861, -1.3763,  0.2987],
         [ 1.5127, -0.4595,  0.1611, -1.2143]]],
       grad_fn=<NativeBatchNormBackward0>)
tensor(4.4703e-08, grad_fn=<MeanBackward0>)


In [8]:
my_tensor = torch.rand(1, 4, 4)
print(my_tensor)

dropout = torch.nn.Dropout(p = 0.4)
print(dropout(my_tensor))
print(dropout(my_tensor))

tensor([[[0.3353, 0.3233, 0.7732, 0.8716],
         [0.1925, 0.1434, 0.6427, 0.3657],
         [0.1662, 0.9275, 0.3714, 0.1314],
         [0.6677, 0.3969, 0.1874, 0.0916]]])
tensor([[[0.0000, 0.5389, 1.2887, 0.0000],
         [0.3208, 0.0000, 1.0711, 0.6096],
         [0.0000, 1.5458, 0.6190, 0.2190],
         [0.0000, 0.0000, 0.3124, 0.1526]]])
tensor([[[0.5589, 0.0000, 1.2887, 1.4526],
         [0.0000, 0.2389, 1.0711, 0.6096],
         [0.2770, 1.5458, 0.0000, 0.2190],
         [1.1128, 0.6615, 0.3124, 0.1526]]])
